import { Manrope } from "next/font/google";
import Image from "next/image";
import "./globals.scss";

const manrope = Manrope({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={manrope.className}>
				<Image
					src={"/img/noisy-shape1.png"}
					alt={"noisy"}
					className="right-top-image"
					width={703}
					height={962}
				/>
				{children}
			</body>
		</html>
	);
}
