name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build and Push the Docker image
      - name: Build Docker image
        run: docker build -t hazratali451/my-portfolio:latest .
      - name: Push Docker image
        run: docker push hazratali451/my-portfolio:latest

      # Step 4: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          port: 22
          script: |
            #Login to Docker Hub
            sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            # Pull the latest Docker image
            docker pull hazratali451/my-portfolio:latest
            # Stop and remove the old container (if exists)
            docker rm -f portfolio || true
            # Run the new container
            docker run -d --restart unless-stopped --name portfolio -p 80:3000 hazratali451/my-portfolio:latest
